cadvisor:
  image: google/cadvisor:latest
  container_name: cadvisor
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - 8080:8080

prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
  links:
    - cadvisor
  ports:
    - 9090:9090

#grafana:
  #image: grafana/grafana
  #container_name: grafana
  #links:
    #- prometheus
  #ports:
    #- 3000:3000
